name: Run build and publish image

on: [push]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Build & Push Image
        - uses: actions/checkout@v2
    
        - name: Build and push image
          run: |
            echo "oi"