name: Publish-image

on:
    workflow_run:
        workflows:
            - "Run-tests"
        types:
            - completed
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Build and push image
          run: |
            const status = '${{ github.event.workflow_run.conclusion }}';
            if (status === 'success') {

                docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}
                docker image build -t ${{secrets.DOCKERHUB_USERNAME}}/server-python:latest .
                docker push ${{secrets.DOCKERHUB_USERNAME}}/server-python:latest
            
                } else {
                console.log('Previous workflow failed or not completed');
                process.exit(1);
            }
            