name: Publish-image

on:
    workflow_run:
        workflows:
            - "Run-tests"
        types:
            - completed
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Build and push image
          run: |
            echo $status
            